package ir.roela.bametro

enum class MapType(val value: String) {
    TEHRAN_METRO("TEHRAN_METRO"),
    METRO_TIMES("METRO_TIMES"),
    TEHRAN_BRT_BUS("TEHRAN_BRT_BUS"),
    TEHRAN_MAP_OFFLINE("TEHRAN_MAP_OFFLINE"),
    TEHRAN_MAP_ONLINE("TEHRAN_MAP_ONLINE"),
    TEHRAN_CEMETERY("TEHRAN_CEMETERY"),
    TEHRAN_MOUNT("TEHRAN_MOUNT"),
    ISFAHAN_METRO("ISFAHAN_METRO"),
    TABRIZ_METRO("TABRIZ_METRO")
}