package ir.roela.bametro.utils

enum class MapType(val value: String) {
    IRAN_NECESSARY_PHONES("IRAN_NECESSARY_PHONES"),
    TEHRAN_METRO("TEHRAN_METRO"),
    TEHRAN_BRT_BUS("TEHRAN_BRT_BUS"),
    TEHRAN_METRO_BRT_COMBINED("TEHRAN_METRO_BRT_COMBINED"),
    TEHRAN_MAP_OFFLINE("TEHRAN_MAP_OFFLINE"),
    TEHRAN_MAP_ONLINE("TEHRAN_MAP_ONLINE"),
    TEHRAN_CEMETERY("TEHRAN_CEMETERY"),
    TEHRAN_MOUNT("TEHRAN_MOUNT"),
    ISFAHAN_METRO("ISFAHAN_METRO"),
    TABRIZ_METRO("TABRIZ_METRO"),
    TEHRAN_BOOK_FAIR("TEHRAN_BOOK_FAIR"),
    ISTANBUL_METRO("ISTANBUL_METRO"),
    DUBAI_METRO("DUBAI_METRO"),
}